# Generated by Django 4.2.3 on 2024-04-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfmodel',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tfmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tfmodel',
            name='loss',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tfmodel',
            name='optimizer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
