# Generated by Django 4.2.3 on 2024-04-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0003_remove_tfmodel_accuracy_remove_tfmodel_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfmodel',
            name='data_augmentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tfmodel',
            name='batch_size',
            field=models.IntegerField(default=16),
        ),
    ]
