# Generated by Django 4.2.3 on 2024-04-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0004_tfmodel_data_augmentation_alter_tfmodel_batch_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='name',
            field=models.CharField(default='training', max_length=100),
            preserve_default=False,
        ),
    ]
