# Generated by Django 4.2.3 on 2024-04-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0006_rename_description_trainingsession_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsession',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Training', 'Training'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
