# Generated by Django 4.2.3 on 2024-04-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0007_rename_timestamp_trainingsession_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Training', 'Training'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=30),
        ),
    ]
