# Generated by Django 4.2.3 on 2024-05-06 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0006_alter_dataset_labels'),
        ('feature_extractor', '0008_alter_trainingsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfmodel',
            name='model_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Training', 'Training'), ('Testing', 'Testing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=30),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Training', 'Training'), ('Testing', 'Testing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='datasets.dataset')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='feature_extractor.trainingsession')),
            ],
        ),
    ]
