# Generated by Django 4.2.3 on 2024-05-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0009_tfmodel_model_path_alter_trainingsession_status_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfmodel',
            name='model_path',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='model_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
