# Generated by Django 4.2.3 on 2024-05-08 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0006_alter_dataset_labels'),
        ('feature_extractor', '0010_remove_tfmodel_model_path_trainingsession_model_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='datasets.image')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='datasets.label')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='feature_extractor.test')),
            ],
        ),
    ]
