# Generated by Django 4.2.3 on 2024-05-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0011_testresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='image',
        ),
        migrations.AddField(
            model_name='testresult',
            name='true_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='prediction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
