# Generated by Django 4.2.3 on 2024-05-14 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0007_alter_dataset_resolution'),
        ('feature_extractor', '0013_tfmodel_pre_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='datasets.image'),
        ),
    ]
