# Generated by Django 4.2.3 on 2024-06-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0016_alter_tfmodel_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='class_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
