# Generated by Django 4.2.3 on 2024-06-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0017_trainingsession_class_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='grad_cam',
            field=models.ImageField(blank=True, null=True, upload_to='grad_cam/'),
        ),
    ]
