# Generated by Django 4.2.3 on 2024-09-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0020_study_trainingsession_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfmodel',
            name='blur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tfmodel',
            name='brightness_contrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tfmodel',
            name='cutout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tfmodel',
            name='gaussian_noise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tfmodel',
            name='grayscale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tfmodel',
            name='horizontal_flip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tfmodel',
            name='random_crop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tfmodel',
            name='random_grayscale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tfmodel',
            name='random_rotation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tfmodel',
            name='vertical_flip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tfmodel',
            name='zoom',
            field=models.BooleanField(default=False),
        ),
    ]