# Generated by Django 4.2.3 on 2024-10-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0021_tfmodel_blur_tfmodel_brightness_contrast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfmodel',
            name='fine_tuning',
            field=models.BooleanField(default=False),
        ),
    ]
