# Generated by Django 4.2.3 on 2026-02-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0024_seed_study_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
