# Generated by Django 4.2.3 on 2026-03-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0025_study_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_synthetic_tools', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='tfmodel',
            name='synthetic_fracture',
            field=models.BooleanField(default=False),
        ),
    ]
