# Generated by Django 4.2.3 on 2026-04-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0026_sitesettings_tfmodel_synthetic_fracture'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='batch_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='learning_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='num_epochs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
