# Generated by Django 4.2.3 on 2026-05-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0027_trainingsession_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='input_mode',
            field=models.CharField(choices=[('image_only', 'Image only (image-only single-input model)'), ('image_plus_size', 'Image + size scalars (multi-input: pixels + length/width/area/completeness in mm)')], default='image_only', max_length=32),
        ),
    ]
